# Generated by Django 3.2.9 on 2021-11-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='available',
            new_name='active',
        ),
    ]
